### ISSUE TITLE
Event error

### ISSUE THREAD

**Issue by tomchadwin** [perliedman/leaflet-multi-style#4]
I'm getting the following:

[Update: replaced minified Leaflet with source, so stack trace makes more sense]

```
Uncaught TypeError: Cannot read property 'addEventParent' of null
    at NewClass.addLayer (leaflet.js:8055:8)
    at NewClass.initialize (leaflet.js:7891:10)
    at new NewClass (leaflet.js:310:20)
    at Function.geometryToLayer (leaflet.js:10518:11)
    at NewClass.addData (leaflet.js:10445:25)
    at NewClass.addData (multi-style-layer.js:44:45)
    at NewClass.addData (leaflet.js:10435:11)
    at NewClass.<anonymous> (multi-style-layer.js:28:53)
    at Array.forEach (native)
    at NewClass.addData (multi-style-layer.js:23:41)
```

Where have we lost `e.addEventParent`?

**Comment by tomchadwin** [comment]
Sorry - my question was incorrect. Why is `layer` null?

**Comment by tomchadwin** [comment]
OK, I think it fails with multipoints. If I convert my layer to single points, it works. Why would only multipoints fail?

**Comment by perliedman** [comment]
Hi,
the reason is the default `pointToLayers` that is in `multi-style-layer.js`'s `options`: it returns `null`. Just removing that from options seems to resolve this issue.

Since I don't actively use this code myself (my own use case contains mostly the same, but more specialized code and is only used from `LineString`s), I can't really tell if that option was there for good reason, but I'll remove it for now - tell me if we need to put it back.

**Comment by perliedman** [comment]
I published version 1.1.1 with this change. Closing for now.

**Comment by tomchadwin** [comment]
Thanks so much! I'll test as soon as I can and hopefully confirm.

**Comment by tomchadwin** [comment]
I'm afraid that's not quite right. The error is gone, for sure, but now, as well as the styled points, default markers are appearing as well:

![2017-06-14 23_35_07-export to web map](https://user-images.githubusercontent.com/7840213/27157583-3663d128-515a-11e7-8bdb-2cada0a605c3.png)

Relevant code is:

```javascript
function style_Pasted0_0() {
    return {
        radius: 4.0,
        opacity: 1,
        color: 'rgba(0,0,0,1.0)',
        weight: 1,
        fillOpacity: 1,
        fillColor: 'rgba(128,76,140,1.0)'
    }
}
var layer_Pasted0 = new L.geoJson.multiStyle(json_Pasted0, {
    pointToLayers: [function (feature, latlng) {
        return L.circleMarker(latlng, style_Pasted0_0(feature))
    }
]});
```
